### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by siyuan126** [MCSands/sql-scratch-capstone-turn-in#1]
**Criteria 1: Report**
Score Level: 3 (Meets Expectations)
Comment(s): Your slides are well designed. The table of contents and splash pages between sections are much appreciated and ease the flow of information. Every answer has three components: 1) SQL queries, 2) output tables as evidence, 3) text interpreting the query results. However, some supporting text was very vague and can't be supported solely by the data . For example, on the advertising campaign slide, you said "some sources are used by multiple campaigns", which sources and multiple is how many. A more accurate interpretation of the data should be something like " CoolTShirts has 1 campaign for each of these sources: nytimes, buzzfeed, facebook, medium. CoolTShirts has 2 campaigns for each of these sources: email, google". Similar issue on typical journey slide. The three conclusion you made are all very vague and left room for interpretation. Please review them later to see if you can make accurate, precise conclusion that don't leave room for a different interpretation for the audience. Also check the last slide. The five campaigns  are not selected because they all contribute to both first touch and last touch. Be specific, which campaigns contribute to which touch. And try to avoid to use words like majority and approximately, use accurate numbers instead. 

**Criteria 2: Query Accuracy**
Score Level: 4 (Exceeds Expectations)
Comment(s): All queries accurately retrieve the data intended. Good job including ORDER BY statements to organize the tables and make interpretation easier!

**Criteria 3: Query Formatting**
Score Level: 4 (Exceeds Expectations)
Comment(s): Queries adhere to at the rules of the style guide. Good work using aliases to rename the columns and using indentation to organize your subqueries, both make your queries more readable!
Criteria 4: Understanding underlying concepts and terminology

**Score Level: 4 (Exceeds Expectations)**
Comment(s): Report demonstrates an above-and-beyond understanding of the dataset. It shows really thought about all components of the data and how they link together. You are the first user I've encountered that made the distinction between "initial" campaigns and "return" campaigns and appreciated the importance of both in the CoolTShirts funnel. The additional calculations of % of total visits and pie chart visualizations show your curiosity and ability to dig into the dataset. Plus, your different recommendations based on the nature of the return campaigns shows that you connected the data to real-life experiences.

**Overall Score: 15/16**
Overall, Great job! Your SQL queries flawless, and presentation is well designed. Sorry being a little picky but I do recommend to work on the interpretation of the data more. Try to be more accurate and precise, use data instead of vague words when describe the results and make conclusion.

**Comment by MCSands** [comment]
Thanks for the feedback.
